import Head from 'next/head'
import fs from 'fs'
import path from 'path'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home({posts}) {
  console.log(posts)
  return (
    <>
      <Head>
        <title>Finch Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Hello</h2>
    </>
  )
}

export async function getStaticProps() {
  //Get files from the posts directory
  const files = fs.readdirSync(path.join('posts'))
  
  //Get slug and frontmatter from posts
  const posts = files.map((filename) => {
    //Create slug
    //We will replace the .md tag with nothing and return the slug
    //We should get an array with the objects with slug and filename
    const slug = filename.replace(".md", "")

    return {
      slug,
    }
  })

  console.log(posts)
  return {
    props: {
      posts: 'The Posts'
    }
  }
}